# This file is automatically generated in base/Makefile
const ARCH = :x86_64
const MACHINE = "x86_64-linux-gnu"
const libm_name = "libopenlibm"
const libblas_name = "libopenblas"
const liblapack_name = "libopenblas"
const USE_BLAS64 = true
const USE_GPL_LIBS = true
const libfftw_name = "libfftw3_threads"
const libfftwf_name = "libfftw3f_threads"
const libllvm_version = "svn"
const VERSION_STRING = "0.4.0-dev"
const TAGGED_RELEASE_BANNER = ""
const SYSCONFDIR = "../etc"
const DATAROOTDIR = "../share"
const DOCDIR = "../share/doc/julia"
