# This file was autogenerated in base/version_git.sh
immutable GitVersionInfo
    commit::AbstractString
    commit_short::AbstractString
    branch::AbstractString
    build_number::Int
    date_string::AbstractString
    tagged_commit::Bool
    fork_master_distance::Int
    fork_master_timestamp::Float64
end

const GIT_VERSION_INFO = GitVersionInfo(
    "fc93a4c6f813b4baee8ba5bdcb1bbd5167d7193e",
    "fc93a4c",
    "master",
    5920,
    "2015-07-10 21:37 UTC",
    false,
    0,
    1436564234.
)
